"""my_new_feature

Revision ID: 469356a460a2
Revises: a07ee6c35bee
Create Date: 2024-06-27 17:30:00.785171

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '469356a460a2'
down_revision = 'a07ee6c35bee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pizza_type', sa.Column('sauce_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'pizza_type', 'sauce', ['sauce_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pizza_type', type_='foreignkey')
    op.drop_column('pizza_type', 'sauce_id')
    # ### end Alembic commands ###
